### PR TITLE
[#10] Let user filter mob by level

### LINKED ISSUE #10: Let user filter mob by level
While using the bot it was clear that it can get messy when dealing with common mobs (that can have multiple levels) because it can sometimes return multiple mobs when only 1 is wanted. We should implement a second argument in the bot call that allows the user to specify a level of that mob so it can return only 1 entry.

### PR DESCRIPTION
**Pull request by edualb**
### **Purpose**
Filter monster by level

### **Solution**
We are filtering by range of site, for example:
If the user digits `!mobt abelha 55`, Tibro will search by name abelha and level range 55 to 200

### **Issue**
close #10

### CODE REVIEW

**Comment by edualb** [comment]
@arxdsilva when you have time, can you check this pull request?

**Comment by arxdsilva** [comment]
sure, just dont forget to fix the conflict problems first :D

**Comment by edualb** [comment]
@arxdsilva where is the conflicts?

**Comment by arxdsilva** [comment]
tibro

**Comment by arxdsilva** [comment]
faz o gif e resolve o conflito, depois faz push dnv :D

**Comment by edualb** [comment]
@arxdsilva The all conflicts was solved before... look [this](https://stackoverflow.com/questions/8523776/git-rebase-continue-complains-even-when-all-merge-conflicts-have-been-resolved). The merge with branch master is [done](https://github.com/edualb/Tibro/commits/develop).

**Comment by arxdsilva** [comment]
vei vo resolver isso aqui

**Comment by arxdsilva** [comment]
@edualb da uma testada agora na master e me diz se quebrou algo

**Pull request merged**
